### ISSUE TITLE
non-power-of-2 images fail to inference

### ISSUE THREAD

**Issue by Manoa1911** [lixinustc/HST-for-Compressed-SR#3]
```Traceback (most recent call last):
  File "floor.py", line 84, in <module>
    E = test(model, img)
  File "floor.py", line 48, in test
    img = model(img)
  File "H:\WPy64-3850\python-3.8.5.amd64\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "X:\HST-for-Compressed-Image-SR-main\model.py", line 147, in forward
    x_l = self.GRSTB_1(x_l)
  File "H:\WPy64-3850\python-3.8.5.amd64\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "X:\HST-for-Compressed-Image-SR-main\model.py", line 66, in forward
    x = layer(x, x_size)
  File "H:\WPy64-3850\python-3.8.5.amd64\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "X:\HST-for-Compressed-Image-SR-main\swin_block.py", line 433, in forward
    return self.patch_embed(self.conv(self.patch_unembed(self.residual_group(x, x_size), x_size))) + x
  File "H:\WPy64-3850\python-3.8.5.amd64\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "X:\HST-for-Compressed-Image-SR-main\swin_block.py", line 353, in forward
    x = blk(x, x_size)
  File "H:\WPy64-3850\python-3.8.5.amd64\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "X:\HST-for-Compressed-Image-SR-main\swin_block.py", line 255, in forward
    x_windows = window_partition(shifted_x, self.window_size)  # nW*B, window_size, window_size, C
  File "X:\HST-for-Compressed-Image-SR-main\swin_block.py", line 43, in window_partition
    x = x.view(B, H // window_size, window_size, W // window_size, window_size, C)
RuntimeError: shape '[1, 31, 8, 15, 8, 60]' is invalid for input of size 1845120```

--windows-size 16384

**Comment by Manoa1911** [comment]
```padding = args.scale * h_old * w_old```
may solve the problem....

**Comment by lixinustc** [comment]
Thanks for your suggestion, we will solve this question in the code

**Comment by Manoa1911** [comment]
images less than 16 pixels in X dimension refuse to inference also
